header: imas Maryanto
title: Notes of programmer
email: software.dimas_m@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog ini adalah catatan penting untuk seorang programmer yang pelupa seperti saya,
  Di Blog ini berisi artikel-artikel yang mengukin berguna dalam pekerjaan sebagai IT Person yang 
  kerjaanya ngurusin segala sesuatu seperti Server Management, Software Engineer, DevOps sampai Networking
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.dimas-maryanto.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dimMaryanto93
github_username:  dimMaryanto93

kramdown:
  input: GFM
  syntax_highlighter: rouge
gist:
  noscript: false

permalink: /notes/:categories/:title

paginate: 5
paginate_path: /pages/page-:num

jekyll-minifier:
  exclude: 'atom.xml'

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    day: '/archives/:year/:month/:day/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'

titlecase: false

plugins:
  - jekyll-gist
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - _docker/
  - vendor
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - package.json
  - README.md
  - CHANGELOG.md
  - CONTRIBUTING.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/